namespace ilf.pgn.Data
{
    public enum MoveAnnotation
    {
        MindBlowing,
        Brilliant,
        Good,
        Interesting,
        Dubious,
        Mistake,
        Blunder,
        Abysmal,
        FascinatingButUnsound,
        Unclear,
        WithCompensation,
        EvenPosition,
        SlightAdvantageWhite,
        SlightAdvantageBlack,
        AdvantageWhite,
        AdvantageBlack,
        DecisiveAdvantageWhite,
        DecisiveAdvantageBlack,
        Space,
        Initiative,
        Development,
        Counterplay,
        Countering,
        Idea,
        TheoreticalNovelty,
        UnknownAnnotation,
    }
}
